### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [jrg1381/smrequestid#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
failed to run the plugin with Yaegi: the load of the plugin takes too much time(10s), or an error, inside the plugin, occurs during the load: 1:21: import "github.com/jrg1381/smrequestid" error: /tmp/traefik-plugin-gop609427337/src/github.com/jrg1381/smrequestid/main.go:21:10: unknown field ResponseHeaderName in struct literal
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by jrg1381** [comment]
fixed
